server:
  port: 8092
  servlet:
    context-path:

spring:
  application:
    name: DEMO-APP
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 800MB
      max-file-size: 800MB
  data:
    redis:
      enable: true
        # Connection URL, will override host, port and password (user will be ignored), e.g. redis://user:password@example.com:6379
        url: redis://127.0.0.1:6379
        timeout: 2000 # 连接或读取超时时长（毫秒）
        database: 7
        redisson:
          file: classpath:redisson.yml
        jedis:
          pool:
            max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 8 # 连接池中的最大空闲连接
            min-idle: 2 # 连接池中的最小空闲连接

logging:
  config: classpath:logback-spring.xml

# 训练数据文件夹的路径
tess4j:
  datapath: D:/tessdata

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
